# Site settings
title:          A Year Of Coding
description:    "Minimal Jekyll theme for storytellers"
url:            "https://chrischris96.github.io/"

# Author
author:
  name:         Christian Plitz
  url:          https://chrischris96.github.io/
  email:        christian.plitz@tum.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
